### ISSUE TITLE
keep js dependencies internal (for offline work) 

### ISSUE THREAD

**Issue by BehindTheBrain** [tvachnad/Neural-Network#11]
Namely, in the simulation_page.html, can we just download anything like this one needed for logging: https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js and keep it in the vendor js folder, rather than get it every time?

Also, the main homepage is waayy to scripty for our minimal needs (sorry Cassie). We could accomplish the same with something vastly simpler than bootstrap.

For both of these, for example if we're at an ONR conference with no internet (they have high security and no wifi allowed), we want to be able to launch the simulation without needing to be online.

**Comment by emmaajordan** [comment]
We could store the jquery library locally in the static folder, but it the standard is to use google or another hosted service since it is likely that the user's browser caches the file and would already have it instead of loading it every time if we host it. 

I think for Cassie's script to work we just need to host the bootstrap files, but I could be wrong this isn't my area of expertise.

**Comment by BehindTheBrain** [comment]
Great. Let's generally stick to keeping all the required js in the static/js/vendor folder, and avoid loading any external www urls, for js or otherwise.

I think the boostrap stuff can be included and stored easily enough, and some is already there.

**Comment by BehindTheBrain** [comment]
Jquery moved to static, for both purplebrain.html and index.html.
